[package]
name = "restman-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
http = "1.4.0"
thiserror = "2.0.17"
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = "1.0.145"
serde_url_params = "0.2.1"
ureq = { version = "3.1.4", features = ["cookies"] }